accounts:
  - name: alice
    coins: ["20000link", "200000000stake"]
  - name: bob
    coins: ["10000link", "100000000stake"]
validator:
  name: alice
  staked: "100000000stake"
faucet:
  name: bob
  coins: ["5link", "100000stake"]
