// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: chainlink/v1beta/query.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GetFeedByIdRequest struct {
	FeedId string `protobuf:"bytes,1,opt,name=feedId,proto3" json:"feedId,omitempty"`
}

func (m *GetFeedByIdRequest) Reset()         { *m = GetFeedByIdRequest{} }
func (m *GetFeedByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetFeedByIdRequest) ProtoMessage()    {}
func (*GetFeedByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_21ba17f95e61a418, []int{0}
}
func (m *GetFeedByIdRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetFeedByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetFeedByIdRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetFeedByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeedByIdRequest.Merge(m, src)
}
func (m *GetFeedByIdRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetFeedByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeedByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeedByIdRequest proto.InternalMessageInfo

func (m *GetFeedByIdRequest) GetFeedId() string {
	if m != nil {
		return m.FeedId
	}
	return ""
}

type GetFeedByIdResponse struct {
	Feed *MsgFeed `protobuf:"bytes,1,opt,name=feed,proto3" json:"feed,omitempty"`
}

func (m *GetFeedByIdResponse) Reset()         { *m = GetFeedByIdResponse{} }
func (m *GetFeedByIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetFeedByIdResponse) ProtoMessage()    {}
func (*GetFeedByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_21ba17f95e61a418, []int{1}
}
func (m *GetFeedByIdResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetFeedByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetFeedByIdResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetFeedByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeedByIdResponse.Merge(m, src)
}
func (m *GetFeedByIdResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetFeedByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeedByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeedByIdResponse proto.InternalMessageInfo

func (m *GetFeedByIdResponse) GetFeed() *MsgFeed {
	if m != nil {
		return m.Feed
	}
	return nil
}

type GetModuleOwnerRequest struct {
}

func (m *GetModuleOwnerRequest) Reset()         { *m = GetModuleOwnerRequest{} }
func (m *GetModuleOwnerRequest) String() string { return proto.CompactTextString(m) }
func (*GetModuleOwnerRequest) ProtoMessage()    {}
func (*GetModuleOwnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_21ba17f95e61a418, []int{2}
}
func (m *GetModuleOwnerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetModuleOwnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetModuleOwnerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetModuleOwnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetModuleOwnerRequest.Merge(m, src)
}
func (m *GetModuleOwnerRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetModuleOwnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetModuleOwnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetModuleOwnerRequest proto.InternalMessageInfo

type GetModuleOwnerResponse struct {
	ModuleOwner []*MsgModuleOwner `protobuf:"bytes,1,rep,name=moduleOwner,proto3" json:"moduleOwner,omitempty"`
}

func (m *GetModuleOwnerResponse) Reset()         { *m = GetModuleOwnerResponse{} }
func (m *GetModuleOwnerResponse) String() string { return proto.CompactTextString(m) }
func (*GetModuleOwnerResponse) ProtoMessage()    {}
func (*GetModuleOwnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_21ba17f95e61a418, []int{3}
}
func (m *GetModuleOwnerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetModuleOwnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetModuleOwnerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetModuleOwnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetModuleOwnerResponse.Merge(m, src)
}
func (m *GetModuleOwnerResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetModuleOwnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetModuleOwnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetModuleOwnerResponse proto.InternalMessageInfo

func (m *GetModuleOwnerResponse) GetModuleOwner() []*MsgModuleOwner {
	if m != nil {
		return m.ModuleOwner
	}
	return nil
}

type GetRoundDataRequest struct {
	FeedId     string             `protobuf:"bytes,1,opt,name=feedId,proto3" json:"feedId,omitempty"`
	RoundId    uint64             `protobuf:"varint,2,opt,name=roundId,proto3" json:"roundId,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *GetRoundDataRequest) Reset()         { *m = GetRoundDataRequest{} }
func (m *GetRoundDataRequest) String() string { return proto.CompactTextString(m) }
func (*GetRoundDataRequest) ProtoMessage()    {}
func (*GetRoundDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_21ba17f95e61a418, []int{4}
}
func (m *GetRoundDataRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetRoundDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetRoundDataRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetRoundDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRoundDataRequest.Merge(m, src)
}
func (m *GetRoundDataRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetRoundDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRoundDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRoundDataRequest proto.InternalMessageInfo

func (m *GetRoundDataRequest) GetFeedId() string {
	if m != nil {
		return m.FeedId
	}
	return ""
}

func (m *GetRoundDataRequest) GetRoundId() uint64 {
	if m != nil {
		return m.RoundId
	}
	return 0
}

func (m *GetRoundDataRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type GetRoundDataResponse struct {
	RoundData  []*RoundData        `protobuf:"bytes,1,rep,name=roundData,proto3" json:"roundData,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *GetRoundDataResponse) Reset()         { *m = GetRoundDataResponse{} }
func (m *GetRoundDataResponse) String() string { return proto.CompactTextString(m) }
func (*GetRoundDataResponse) ProtoMessage()    {}
func (*GetRoundDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_21ba17f95e61a418, []int{5}
}
func (m *GetRoundDataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetRoundDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetRoundDataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetRoundDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRoundDataResponse.Merge(m, src)
}
func (m *GetRoundDataResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetRoundDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRoundDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRoundDataResponse proto.InternalMessageInfo

func (m *GetRoundDataResponse) GetRoundData() []*RoundData {
	if m != nil {
		return m.RoundData
	}
	return nil
}

func (m *GetRoundDataResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type GetLatestRoundDataRequest struct {
	FeedId string `protobuf:"bytes,1,opt,name=feedId,proto3" json:"feedId,omitempty"`
}

func (m *GetLatestRoundDataRequest) Reset()         { *m = GetLatestRoundDataRequest{} }
func (m *GetLatestRoundDataRequest) String() string { return proto.CompactTextString(m) }
func (*GetLatestRoundDataRequest) ProtoMessage()    {}
func (*GetLatestRoundDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_21ba17f95e61a418, []int{6}
}
func (m *GetLatestRoundDataRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetLatestRoundDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetLatestRoundDataRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetLatestRoundDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLatestRoundDataRequest.Merge(m, src)
}
func (m *GetLatestRoundDataRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetLatestRoundDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLatestRoundDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLatestRoundDataRequest proto.InternalMessageInfo

func (m *GetLatestRoundDataRequest) GetFeedId() string {
	if m != nil {
		return m.FeedId
	}
	return ""
}

type GetLatestRoundDataResponse struct {
	RoundData []*RoundData `protobuf:"bytes,1,rep,name=roundData,proto3" json:"roundData,omitempty"`
}

func (m *GetLatestRoundDataResponse) Reset()         { *m = GetLatestRoundDataResponse{} }
func (m *GetLatestRoundDataResponse) String() string { return proto.CompactTextString(m) }
func (*GetLatestRoundDataResponse) ProtoMessage()    {}
func (*GetLatestRoundDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_21ba17f95e61a418, []int{7}
}
func (m *GetLatestRoundDataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetLatestRoundDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetLatestRoundDataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetLatestRoundDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLatestRoundDataResponse.Merge(m, src)
}
func (m *GetLatestRoundDataResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetLatestRoundDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLatestRoundDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLatestRoundDataResponse proto.InternalMessageInfo

func (m *GetLatestRoundDataResponse) GetRoundData() []*RoundData {
	if m != nil {
		return m.RoundData
	}
	return nil
}

type RoundData struct {
	FeedId   string         `protobuf:"bytes,1,opt,name=feedId,proto3" json:"feedId,omitempty"`
	FeedData *OCRAbiEncoded `protobuf:"bytes,2,opt,name=feedData,proto3" json:"feedData,omitempty"`
}

func (m *RoundData) Reset()         { *m = RoundData{} }
func (m *RoundData) String() string { return proto.CompactTextString(m) }
func (*RoundData) ProtoMessage()    {}
func (*RoundData) Descriptor() ([]byte, []int) {
	return fileDescriptor_21ba17f95e61a418, []int{8}
}
func (m *RoundData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RoundData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RoundData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RoundData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoundData.Merge(m, src)
}
func (m *RoundData) XXX_Size() int {
	return m.Size()
}
func (m *RoundData) XXX_DiscardUnknown() {
	xxx_messageInfo_RoundData.DiscardUnknown(m)
}

var xxx_messageInfo_RoundData proto.InternalMessageInfo

func (m *RoundData) GetFeedId() string {
	if m != nil {
		return m.FeedId
	}
	return ""
}

func (m *RoundData) GetFeedData() *OCRAbiEncoded {
	if m != nil {
		return m.FeedData
	}
	return nil
}

type GetAccountRequest struct {
	AccountAddress github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,1,opt,name=accountAddress,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"accountAddress,omitempty"`
}

func (m *GetAccountRequest) Reset()         { *m = GetAccountRequest{} }
func (m *GetAccountRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountRequest) ProtoMessage()    {}
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_21ba17f95e61a418, []int{9}
}
func (m *GetAccountRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetAccountRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountRequest.Merge(m, src)
}
func (m *GetAccountRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountRequest proto.InternalMessageInfo

func (m *GetAccountRequest) GetAccountAddress() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.AccountAddress
	}
	return nil
}

type GetAccountResponse struct {
	Account *MsgAccount `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
}

func (m *GetAccountResponse) Reset()         { *m = GetAccountResponse{} }
func (m *GetAccountResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountResponse) ProtoMessage()    {}
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_21ba17f95e61a418, []int{10}
}
func (m *GetAccountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetAccountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountResponse.Merge(m, src)
}
func (m *GetAccountResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountResponse proto.InternalMessageInfo

func (m *GetAccountResponse) GetAccount() *MsgAccount {
	if m != nil {
		return m.Account
	}
	return nil
}

type GetFeedRewardAvailStrategiesRequest struct {
}

func (m *GetFeedRewardAvailStrategiesRequest) Reset()         { *m = GetFeedRewardAvailStrategiesRequest{} }
func (m *GetFeedRewardAvailStrategiesRequest) String() string { return proto.CompactTextString(m) }
func (*GetFeedRewardAvailStrategiesRequest) ProtoMessage()    {}
func (*GetFeedRewardAvailStrategiesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_21ba17f95e61a418, []int{11}
}
func (m *GetFeedRewardAvailStrategiesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetFeedRewardAvailStrategiesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetFeedRewardAvailStrategiesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetFeedRewardAvailStrategiesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeedRewardAvailStrategiesRequest.Merge(m, src)
}
func (m *GetFeedRewardAvailStrategiesRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetFeedRewardAvailStrategiesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeedRewardAvailStrategiesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeedRewardAvailStrategiesRequest proto.InternalMessageInfo

type GetFeedRewardAvailStrategiesResponse struct {
	AvailStrategies []string `protobuf:"bytes,1,rep,name=availStrategies,proto3" json:"availStrategies,omitempty"`
}

func (m *GetFeedRewardAvailStrategiesResponse) Reset()         { *m = GetFeedRewardAvailStrategiesResponse{} }
func (m *GetFeedRewardAvailStrategiesResponse) String() string { return proto.CompactTextString(m) }
func (*GetFeedRewardAvailStrategiesResponse) ProtoMessage()    {}
func (*GetFeedRewardAvailStrategiesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_21ba17f95e61a418, []int{12}
}
func (m *GetFeedRewardAvailStrategiesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetFeedRewardAvailStrategiesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetFeedRewardAvailStrategiesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetFeedRewardAvailStrategiesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeedRewardAvailStrategiesResponse.Merge(m, src)
}
func (m *GetFeedRewardAvailStrategiesResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetFeedRewardAvailStrategiesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeedRewardAvailStrategiesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeedRewardAvailStrategiesResponse proto.InternalMessageInfo

func (m *GetFeedRewardAvailStrategiesResponse) GetAvailStrategies() []string {
	if m != nil {
		return m.AvailStrategies
	}
	return nil
}

func init() {
	proto.RegisterType((*GetFeedByIdRequest)(nil), "chainlink.v1beta.GetFeedByIdRequest")
	proto.RegisterType((*GetFeedByIdResponse)(nil), "chainlink.v1beta.GetFeedByIdResponse")
	proto.RegisterType((*GetModuleOwnerRequest)(nil), "chainlink.v1beta.GetModuleOwnerRequest")
	proto.RegisterType((*GetModuleOwnerResponse)(nil), "chainlink.v1beta.GetModuleOwnerResponse")
	proto.RegisterType((*GetRoundDataRequest)(nil), "chainlink.v1beta.GetRoundDataRequest")
	proto.RegisterType((*GetRoundDataResponse)(nil), "chainlink.v1beta.GetRoundDataResponse")
	proto.RegisterType((*GetLatestRoundDataRequest)(nil), "chainlink.v1beta.GetLatestRoundDataRequest")
	proto.RegisterType((*GetLatestRoundDataResponse)(nil), "chainlink.v1beta.GetLatestRoundDataResponse")
	proto.RegisterType((*RoundData)(nil), "chainlink.v1beta.RoundData")
	proto.RegisterType((*GetAccountRequest)(nil), "chainlink.v1beta.GetAccountRequest")
	proto.RegisterType((*GetAccountResponse)(nil), "chainlink.v1beta.GetAccountResponse")
	proto.RegisterType((*GetFeedRewardAvailStrategiesRequest)(nil), "chainlink.v1beta.GetFeedRewardAvailStrategiesRequest")
	proto.RegisterType((*GetFeedRewardAvailStrategiesResponse)(nil), "chainlink.v1beta.GetFeedRewardAvailStrategiesResponse")
}

func init() { proto.RegisterFile("chainlink/v1beta/query.proto", fileDescriptor_21ba17f95e61a418) }

var fileDescriptor_21ba17f95e61a418 = []byte{
	// 849 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xc1, 0x4e, 0xeb, 0x46,
	0x14, 0xc5, 0x40, 0xa1, 0x19, 0x10, 0xb4, 0x53, 0x0a, 0x89, 0x8b, 0x92, 0xd4, 0x84, 0x10, 0xd1,
	0xc4, 0x23, 0x82, 0xa0, 0xaa, 0xba, 0x4a, 0xa0, 0x44, 0x91, 0x40, 0x80, 0x59, 0x54, 0xad, 0xba,
	0xe8, 0xc4, 0x1e, 0x8c, 0x45, 0xf0, 0x04, 0x7b, 0x02, 0x44, 0x88, 0x4d, 0x37, 0x2c, 0xa9, 0xd4,
	0xae, 0xd8, 0xf4, 0x43, 0xfa, 0x03, 0x5d, 0x22, 0x75, 0xd3, 0x55, 0xf5, 0x04, 0xef, 0x2b, 0xde,
	0xea, 0xc9, 0xe3, 0x49, 0xec, 0xc4, 0x86, 0xf0, 0xf4, 0x56, 0x8c, 0x67, 0xce, 0x99, 0x7b, 0xee,
	0xdc, 0x7b, 0x2e, 0x01, 0x8b, 0xfa, 0x09, 0xb6, 0xec, 0xa6, 0x65, 0x9f, 0xa2, 0x8b, 0xb5, 0x06,
	0x61, 0x18, 0x9d, 0xb7, 0x89, 0xd3, 0x51, 0x5b, 0x0e, 0x65, 0x14, 0x7e, 0xd6, 0x3b, 0x55, 0xfd,
	0x53, 0x79, 0x55, 0xa7, 0xee, 0x19, 0x75, 0x51, 0x03, 0xbb, 0xc4, 0x87, 0x0a, 0xde, 0x1a, 0x6a,
	0x61, 0xd3, 0xb2, 0x31, 0xb3, 0xa8, 0xed, 0xb3, 0xe5, 0x54, 0xe4, 0x6e, 0x76, 0x25, 0x8e, 0x16,
	0x4d, 0x4a, 0xcd, 0x26, 0x41, 0xb8, 0x65, 0x21, 0x6c, 0xdb, 0x94, 0x71, 0x9e, 0x2b, 0x4e, 0xd3,
	0x11, 0xa2, 0x49, 0x6c, 0xe2, 0x5a, 0xdd, 0xf3, 0x39, 0x93, 0x9a, 0x94, 0x2f, 0x91, 0xb7, 0xf2,
	0x77, 0x95, 0x22, 0x80, 0x35, 0xc2, 0x76, 0x08, 0x31, 0xaa, 0x9d, 0xba, 0xa1, 0x91, 0xf3, 0x36,
	0x71, 0x19, 0x9c, 0x07, 0x13, 0xc7, 0x84, 0x18, 0x75, 0x23, 0x29, 0x65, 0xa5, 0x42, 0x42, 0x13,
	0x5f, 0xca, 0x36, 0xf8, 0xa2, 0x0f, 0xed, 0xb6, 0xa8, 0xed, 0x12, 0x58, 0x02, 0xe3, 0x1e, 0x80,
	0x83, 0xa7, 0xca, 0x29, 0x75, 0xf0, 0x01, 0xd4, 0x3d, 0xd7, 0xf4, 0x48, 0x1a, 0x87, 0x29, 0x0b,
	0xe0, 0xcb, 0x1a, 0x61, 0x7b, 0xd4, 0x68, 0x37, 0xc9, 0xfe, 0xa5, 0x4d, 0x1c, 0x11, 0x56, 0xf9,
	0x05, 0xcc, 0x0f, 0x1e, 0x88, 0x08, 0x55, 0x30, 0x75, 0x16, 0x6c, 0x27, 0xa5, 0xec, 0x58, 0x61,
	0xaa, 0x9c, 0x8d, 0x0d, 0x14, 0xa6, 0x87, 0x49, 0xca, 0x9d, 0xc4, 0xd5, 0x6b, 0xb4, 0x6d, 0x1b,
	0xdb, 0x98, 0xe1, 0x21, 0xc9, 0xc2, 0x24, 0x98, 0x74, 0x3c, 0x6c, 0xdd, 0x48, 0x8e, 0x66, 0xa5,
	0xc2, 0xb8, 0xd6, 0xfd, 0x84, 0x3b, 0x00, 0x04, 0x75, 0x4b, 0x8e, 0xf1, 0xac, 0xf3, 0xaa, 0x5f,
	0x64, 0xd5, 0x2b, 0xb2, 0xea, 0xf7, 0x83, 0x28, 0xb2, 0x7a, 0x80, 0x4d, 0x22, 0xa2, 0x69, 0x21,
	0xa6, 0x72, 0x2f, 0x81, 0xb9, 0x7e, 0x45, 0x22, 0xdd, 0xef, 0x40, 0xc2, 0xe9, 0x6e, 0x8a, 0x64,
	0xbf, 0x8a, 0x26, 0x1b, 0xf0, 0x02, 0x34, 0xac, 0xf5, 0x69, 0x1b, 0xe5, 0xda, 0x56, 0x86, 0x6a,
	0xf3, 0xe3, 0xf6, 0x89, 0x5b, 0x07, 0xa9, 0x1a, 0x61, 0xbb, 0x98, 0x79, 0xaa, 0x5f, 0xf9, 0x66,
	0xca, 0x8f, 0x40, 0x8e, 0x23, 0x7d, 0x74, 0x5a, 0xca, 0xaf, 0x20, 0xd1, 0xdb, 0x7f, 0xb6, 0x62,
	0xdf, 0x83, 0x4f, 0xbd, 0x15, 0xbf, 0xde, 0xcf, 0x3c, 0x13, 0xbd, 0x7e, 0x7f, 0x4b, 0xab, 0x34,
	0xac, 0x1f, 0x6c, 0x9d, 0x1a, 0xc4, 0xd0, 0x7a, 0x04, 0xc5, 0x06, 0x9f, 0xd7, 0x08, 0xab, 0xe8,
	0x3a, 0x6d, 0xdb, 0xac, 0x9b, 0xe7, 0x4f, 0x60, 0x06, 0xfb, 0x3b, 0x15, 0xc3, 0x70, 0x88, 0xeb,
	0xf2, 0x88, 0xd3, 0xd5, 0xb5, 0x77, 0xff, 0x67, 0x4a, 0xa6, 0xc5, 0x4e, 0xda, 0x0d, 0x55, 0xa7,
	0x67, 0x48, 0x18, 0xdc, 0xff, 0x53, 0x72, 0x8d, 0x53, 0xc4, 0x3a, 0x2d, 0xe2, 0xaa, 0x15, 0x5d,
	0x17, 0x44, 0x6d, 0xe0, 0x22, 0x65, 0x97, 0x3b, 0xaf, 0x17, 0x4f, 0x3c, 0xd1, 0x26, 0x98, 0x14,
	0x38, 0xe1, 0xa6, 0xc5, 0xd8, 0x26, 0xef, 0xd2, 0xba, 0x60, 0x65, 0x19, 0x2c, 0x09, 0x67, 0x6a,
	0xe4, 0x12, 0x3b, 0x46, 0xe5, 0x02, 0x5b, 0xcd, 0x23, 0xe6, 0x60, 0x46, 0x4c, 0x8b, 0xb8, 0x5d,
	0x87, 0x1d, 0x80, 0xdc, 0xcb, 0x30, 0x21, 0xa3, 0x00, 0x66, 0x71, 0xff, 0x11, 0xaf, 0x57, 0x42,
	0x1b, 0xdc, 0x2e, 0xff, 0x35, 0x09, 0x3e, 0x39, 0xf4, 0x3a, 0x0a, 0xfe, 0x29, 0x81, 0xe9, 0x70,
	0x37, 0xc3, 0xe5, 0xa8, 0xf4, 0x18, 0xff, 0xc9, 0xf9, 0x61, 0x30, 0x5f, 0x93, 0xb2, 0xf1, 0xdb,
	0xbf, 0x6f, 0xff, 0x18, 0x45, 0xb0, 0x84, 0x82, 0x49, 0xe7, 0x55, 0x0f, 0x19, 0x98, 0x61, 0xc4,
	0x5b, 0x05, 0x5d, 0x0b, 0x8b, 0xde, 0xa0, 0x6b, 0xbf, 0x27, 0x6e, 0xe0, 0xbd, 0x04, 0x66, 0x07,
	0x1a, 0x12, 0x7e, 0x13, 0x1b, 0x32, 0xbe, 0xd7, 0xe5, 0xe2, 0xeb, 0xc0, 0x42, 0x65, 0x91, 0xab,
	0xcc, 0xc3, 0x5c, 0xac, 0xca, 0x26, 0x67, 0x05, 0xe2, 0x6e, 0x25, 0xbf, 0xeb, 0x9a, 0xcd, 0xd0,
	0xd8, 0x82, 0x2b, 0xb1, 0x11, 0xa3, 0x03, 0x53, 0x2e, 0x0c, 0x07, 0x0a, 0x59, 0x19, 0x2e, 0x2b,
	0x05, 0x17, 0x42, 0xb2, 0xfc, 0xe1, 0x88, 0x28, 0x8f, 0x79, 0x2b, 0x81, 0xd9, 0xde, 0x6c, 0xdf,
	0xf1, 0xfd, 0x94, 0x8b, 0xbd, 0x7e, 0xe0, 0x9f, 0x85, 0xbc, 0x3c, 0x04, 0x25, 0x14, 0xac, 0x70,
	0x05, 0x5f, 0xc3, 0x4c, 0x54, 0x01, 0x7f, 0x9f, 0xde, 0x9b, 0xdc, 0x49, 0x60, 0x26, 0x70, 0x46,
	0xdd, 0x3e, 0xa6, 0x70, 0x29, 0x36, 0x44, 0xbf, 0x57, 0xe5, 0xdc, 0xcb, 0x20, 0x21, 0xa3, 0xcc,
	0x65, 0x14, 0xe1, 0x6a, 0x54, 0x86, 0xf0, 0x12, 0xba, 0xee, 0x77, 0xea, 0x0d, 0xfc, 0x5b, 0xe2,
	0x63, 0x2d, 0xde, 0x36, 0x1d, 0xb8, 0xf1, 0xec, 0x03, 0xbc, 0xe4, 0x45, 0x79, 0xf3, 0x43, 0x69,
	0x22, 0x03, 0x95, 0x67, 0x50, 0x80, 0xf9, 0x67, 0x1e, 0xd2, 0xe1, 0x6c, 0xe4, 0x0a, 0x79, 0xd5,
	0xc3, 0x7f, 0x1e, 0xd3, 0xd2, 0xc3, 0x63, 0x5a, 0x7a, 0xf3, 0x98, 0x96, 0x7e, 0x7f, 0x4a, 0x8f,
	0x3c, 0x3c, 0xa5, 0x47, 0xfe, 0x7b, 0x4a, 0x8f, 0xfc, 0xfc, 0x6d, 0x68, 0x82, 0x6d, 0x79, 0x77,
	0x1d, 0xe1, 0x63, 0x12, 0xdc, 0x5a, 0x12, 0x53, 0xed, 0x2a, 0x14, 0x88, 0x8f, 0xb5, 0xc6, 0x04,
	0xff, 0xf1, 0xb0, 0xfe, 0x3e, 0x00, 0x00, 0xff, 0xff, 0xd1, 0xbb, 0xd8, 0xba, 0x09, 0x09, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	GetRoundData(ctx context.Context, in *GetRoundDataRequest, opts ...grpc.CallOption) (*GetRoundDataResponse, error)
	LatestRoundData(ctx context.Context, in *GetLatestRoundDataRequest, opts ...grpc.CallOption) (*GetLatestRoundDataResponse, error)
	GetAllModuleOwner(ctx context.Context, in *GetModuleOwnerRequest, opts ...grpc.CallOption) (*GetModuleOwnerResponse, error)
	GetFeedByFeedId(ctx context.Context, in *GetFeedByIdRequest, opts ...grpc.CallOption) (*GetFeedByIdResponse, error)
	GetAccountInfo(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error)
	GetFeedRewardAvailStrategy(ctx context.Context, in *GetFeedRewardAvailStrategiesRequest, opts ...grpc.CallOption) (*GetFeedRewardAvailStrategiesResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) GetRoundData(ctx context.Context, in *GetRoundDataRequest, opts ...grpc.CallOption) (*GetRoundDataResponse, error) {
	out := new(GetRoundDataResponse)
	err := c.cc.Invoke(ctx, "/chainlink.v1beta.Query/GetRoundData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LatestRoundData(ctx context.Context, in *GetLatestRoundDataRequest, opts ...grpc.CallOption) (*GetLatestRoundDataResponse, error) {
	out := new(GetLatestRoundDataResponse)
	err := c.cc.Invoke(ctx, "/chainlink.v1beta.Query/LatestRoundData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetAllModuleOwner(ctx context.Context, in *GetModuleOwnerRequest, opts ...grpc.CallOption) (*GetModuleOwnerResponse, error) {
	out := new(GetModuleOwnerResponse)
	err := c.cc.Invoke(ctx, "/chainlink.v1beta.Query/GetAllModuleOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetFeedByFeedId(ctx context.Context, in *GetFeedByIdRequest, opts ...grpc.CallOption) (*GetFeedByIdResponse, error) {
	out := new(GetFeedByIdResponse)
	err := c.cc.Invoke(ctx, "/chainlink.v1beta.Query/GetFeedByFeedId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetAccountInfo(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error) {
	out := new(GetAccountResponse)
	err := c.cc.Invoke(ctx, "/chainlink.v1beta.Query/GetAccountInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetFeedRewardAvailStrategy(ctx context.Context, in *GetFeedRewardAvailStrategiesRequest, opts ...grpc.CallOption) (*GetFeedRewardAvailStrategiesResponse, error) {
	out := new(GetFeedRewardAvailStrategiesResponse)
	err := c.cc.Invoke(ctx, "/chainlink.v1beta.Query/GetFeedRewardAvailStrategy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	GetRoundData(context.Context, *GetRoundDataRequest) (*GetRoundDataResponse, error)
	LatestRoundData(context.Context, *GetLatestRoundDataRequest) (*GetLatestRoundDataResponse, error)
	GetAllModuleOwner(context.Context, *GetModuleOwnerRequest) (*GetModuleOwnerResponse, error)
	GetFeedByFeedId(context.Context, *GetFeedByIdRequest) (*GetFeedByIdResponse, error)
	GetAccountInfo(context.Context, *GetAccountRequest) (*GetAccountResponse, error)
	GetFeedRewardAvailStrategy(context.Context, *GetFeedRewardAvailStrategiesRequest) (*GetFeedRewardAvailStrategiesResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) GetRoundData(ctx context.Context, req *GetRoundDataRequest) (*GetRoundDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoundData not implemented")
}
func (*UnimplementedQueryServer) LatestRoundData(ctx context.Context, req *GetLatestRoundDataRequest) (*GetLatestRoundDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LatestRoundData not implemented")
}
func (*UnimplementedQueryServer) GetAllModuleOwner(ctx context.Context, req *GetModuleOwnerRequest) (*GetModuleOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllModuleOwner not implemented")
}
func (*UnimplementedQueryServer) GetFeedByFeedId(ctx context.Context, req *GetFeedByIdRequest) (*GetFeedByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeedByFeedId not implemented")
}
func (*UnimplementedQueryServer) GetAccountInfo(ctx context.Context, req *GetAccountRequest) (*GetAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountInfo not implemented")
}
func (*UnimplementedQueryServer) GetFeedRewardAvailStrategy(ctx context.Context, req *GetFeedRewardAvailStrategiesRequest) (*GetFeedRewardAvailStrategiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeedRewardAvailStrategy not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_GetRoundData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoundDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetRoundData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chainlink.v1beta.Query/GetRoundData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetRoundData(ctx, req.(*GetRoundDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LatestRoundData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestRoundDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LatestRoundData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chainlink.v1beta.Query/LatestRoundData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LatestRoundData(ctx, req.(*GetLatestRoundDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetAllModuleOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModuleOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetAllModuleOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chainlink.v1beta.Query/GetAllModuleOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetAllModuleOwner(ctx, req.(*GetModuleOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetFeedByFeedId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetFeedByFeedId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chainlink.v1beta.Query/GetFeedByFeedId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetFeedByFeedId(ctx, req.(*GetFeedByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetAccountInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetAccountInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chainlink.v1beta.Query/GetAccountInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetAccountInfo(ctx, req.(*GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetFeedRewardAvailStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedRewardAvailStrategiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetFeedRewardAvailStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chainlink.v1beta.Query/GetFeedRewardAvailStrategy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetFeedRewardAvailStrategy(ctx, req.(*GetFeedRewardAvailStrategiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chainlink.v1beta.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRoundData",
			Handler:    _Query_GetRoundData_Handler,
		},
		{
			MethodName: "LatestRoundData",
			Handler:    _Query_LatestRoundData_Handler,
		},
		{
			MethodName: "GetAllModuleOwner",
			Handler:    _Query_GetAllModuleOwner_Handler,
		},
		{
			MethodName: "GetFeedByFeedId",
			Handler:    _Query_GetFeedByFeedId_Handler,
		},
		{
			MethodName: "GetAccountInfo",
			Handler:    _Query_GetAccountInfo_Handler,
		},
		{
			MethodName: "GetFeedRewardAvailStrategy",
			Handler:    _Query_GetFeedRewardAvailStrategy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chainlink/v1beta/query.proto",
}

func (m *GetFeedByIdRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetFeedByIdRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetFeedByIdRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FeedId) > 0 {
		i -= len(m.FeedId)
		copy(dAtA[i:], m.FeedId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.FeedId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetFeedByIdResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetFeedByIdResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetFeedByIdResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Feed != nil {
		{
			size, err := m.Feed.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetModuleOwnerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetModuleOwnerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetModuleOwnerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GetModuleOwnerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetModuleOwnerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetModuleOwnerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ModuleOwner) > 0 {
		for iNdEx := len(m.ModuleOwner) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ModuleOwner[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *GetRoundDataRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetRoundDataRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetRoundDataRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.RoundId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.RoundId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.FeedId) > 0 {
		i -= len(m.FeedId)
		copy(dAtA[i:], m.FeedId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.FeedId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetRoundDataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetRoundDataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetRoundDataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.RoundData) > 0 {
		for iNdEx := len(m.RoundData) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RoundData[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *GetLatestRoundDataRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetLatestRoundDataRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetLatestRoundDataRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FeedId) > 0 {
		i -= len(m.FeedId)
		copy(dAtA[i:], m.FeedId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.FeedId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetLatestRoundDataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetLatestRoundDataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetLatestRoundDataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RoundData) > 0 {
		for iNdEx := len(m.RoundData) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RoundData[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *RoundData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RoundData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RoundData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FeedData != nil {
		{
			size, err := m.FeedData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.FeedId) > 0 {
		i -= len(m.FeedId)
		copy(dAtA[i:], m.FeedId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.FeedId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetAccountRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetAccountRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetAccountRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AccountAddress) > 0 {
		i -= len(m.AccountAddress)
		copy(dAtA[i:], m.AccountAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.AccountAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetAccountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetAccountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetAccountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Account != nil {
		{
			size, err := m.Account.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetFeedRewardAvailStrategiesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetFeedRewardAvailStrategiesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetFeedRewardAvailStrategiesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GetFeedRewardAvailStrategiesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetFeedRewardAvailStrategiesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetFeedRewardAvailStrategiesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AvailStrategies) > 0 {
		for iNdEx := len(m.AvailStrategies) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AvailStrategies[iNdEx])
			copy(dAtA[i:], m.AvailStrategies[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.AvailStrategies[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GetFeedByIdRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FeedId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *GetFeedByIdResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Feed != nil {
		l = m.Feed.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *GetModuleOwnerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GetModuleOwnerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ModuleOwner) > 0 {
		for _, e := range m.ModuleOwner {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *GetRoundDataRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FeedId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.RoundId != 0 {
		n += 1 + sovQuery(uint64(m.RoundId))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *GetRoundDataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.RoundData) > 0 {
		for _, e := range m.RoundData {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *GetLatestRoundDataRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FeedId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *GetLatestRoundDataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.RoundData) > 0 {
		for _, e := range m.RoundData {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *RoundData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FeedId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.FeedData != nil {
		l = m.FeedData.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *GetAccountRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AccountAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *GetAccountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Account != nil {
		l = m.Account.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *GetFeedRewardAvailStrategiesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GetFeedRewardAvailStrategiesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AvailStrategies) > 0 {
		for _, s := range m.AvailStrategies {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GetFeedByIdRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetFeedByIdRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetFeedByIdRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeedId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeedId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetFeedByIdResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetFeedByIdResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetFeedByIdResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Feed", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Feed == nil {
				m.Feed = &MsgFeed{}
			}
			if err := m.Feed.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetModuleOwnerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetModuleOwnerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetModuleOwnerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetModuleOwnerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetModuleOwnerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetModuleOwnerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModuleOwner", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModuleOwner = append(m.ModuleOwner, &MsgModuleOwner{})
			if err := m.ModuleOwner[len(m.ModuleOwner)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetRoundDataRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetRoundDataRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetRoundDataRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeedId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeedId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoundId", wireType)
			}
			m.RoundId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RoundId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetRoundDataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetRoundDataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetRoundDataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoundData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RoundData = append(m.RoundData, &RoundData{})
			if err := m.RoundData[len(m.RoundData)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetLatestRoundDataRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetLatestRoundDataRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetLatestRoundDataRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeedId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeedId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetLatestRoundDataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetLatestRoundDataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetLatestRoundDataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoundData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RoundData = append(m.RoundData, &RoundData{})
			if err := m.RoundData[len(m.RoundData)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RoundData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RoundData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RoundData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeedId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeedId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeedData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.FeedData == nil {
				m.FeedData = &OCRAbiEncoded{}
			}
			if err := m.FeedData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetAccountRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetAccountRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetAccountRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccountAddress = append(m.AccountAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.AccountAddress == nil {
				m.AccountAddress = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetAccountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetAccountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetAccountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Account == nil {
				m.Account = &MsgAccount{}
			}
			if err := m.Account.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetFeedRewardAvailStrategiesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetFeedRewardAvailStrategiesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetFeedRewardAvailStrategiesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetFeedRewardAvailStrategiesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetFeedRewardAvailStrategiesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetFeedRewardAvailStrategiesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvailStrategies", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AvailStrategies = append(m.AvailStrategies, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
