// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: chainlink/v1beta/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryFeedDataRequest struct {
	FeedId     string             `protobuf:"bytes,1,opt,name=feedId,proto3" json:"feedId,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryFeedDataRequest) Reset()         { *m = QueryFeedDataRequest{} }
func (m *QueryFeedDataRequest) String() string { return proto.CompactTextString(m) }
func (*QueryFeedDataRequest) ProtoMessage()    {}
func (*QueryFeedDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_21ba17f95e61a418, []int{0}
}
func (m *QueryFeedDataRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFeedDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFeedDataRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFeedDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFeedDataRequest.Merge(m, src)
}
func (m *QueryFeedDataRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryFeedDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFeedDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFeedDataRequest proto.InternalMessageInfo

func (m *QueryFeedDataRequest) GetFeedId() string {
	if m != nil {
		return m.FeedId
	}
	return ""
}

func (m *QueryFeedDataRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryFeedDataResponse struct {
	FeedData   []*MsgFeedData      `protobuf:"bytes,1,rep,name=feedData,proto3" json:"feedData,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryFeedDataResponse) Reset()         { *m = QueryFeedDataResponse{} }
func (m *QueryFeedDataResponse) String() string { return proto.CompactTextString(m) }
func (*QueryFeedDataResponse) ProtoMessage()    {}
func (*QueryFeedDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_21ba17f95e61a418, []int{1}
}
func (m *QueryFeedDataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFeedDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFeedDataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFeedDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFeedDataResponse.Merge(m, src)
}
func (m *QueryFeedDataResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryFeedDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFeedDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFeedDataResponse proto.InternalMessageInfo

func (m *QueryFeedDataResponse) GetFeedData() []*MsgFeedData {
	if m != nil {
		return m.FeedData
	}
	return nil
}

func (m *QueryFeedDataResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryFeedDataRequest)(nil), "chainlink.v1beta.QueryFeedDataRequest")
	proto.RegisterType((*QueryFeedDataResponse)(nil), "chainlink.v1beta.QueryFeedDataResponse")
}

func init() { proto.RegisterFile("chainlink/v1beta/query.proto", fileDescriptor_21ba17f95e61a418) }

var fileDescriptor_21ba17f95e61a418 = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x41, 0x4b, 0x32, 0x41,
	0x1c, 0xc6, 0x1d, 0x5f, 0x5e, 0x79, 0xdf, 0xb1, 0x43, 0x0c, 0x15, 0x26, 0xb6, 0x2c, 0x7b, 0xd0,
	0x25, 0x68, 0x06, 0xed, 0x10, 0x5d, 0x4d, 0x0c, 0x0f, 0x41, 0xda, 0xad, 0xdb, 0xac, 0x3b, 0xae,
	0x4b, 0xba, 0xb3, 0x3a, 0xa3, 0x28, 0xd1, 0xa5, 0x5b, 0xb7, 0xc0, 0x63, 0x5f, 0xa8, 0xa3, 0xd0,
	0xa5, 0x63, 0x68, 0x1f, 0x24, 0xd6, 0x99, 0x74, 0x51, 0xc1, 0xe3, 0xee, 0xf3, 0x7f, 0x9e, 0xe7,
	0x37, 0xff, 0x19, 0x98, 0x6b, 0xb6, 0xa9, 0x1f, 0x74, 0xfc, 0xe0, 0x81, 0x0c, 0x8b, 0x0e, 0x93,
	0x94, 0xf4, 0x06, 0xac, 0x3f, 0xc6, 0x61, 0x9f, 0x4b, 0x8e, 0xf6, 0x97, 0x2a, 0x56, 0x6a, 0xf6,
	0xb4, 0xc9, 0x45, 0x97, 0x0b, 0xe2, 0x50, 0xc1, 0xd4, 0xa8, 0xf6, 0x15, 0x49, 0x48, 0x3d, 0x3f,
	0xa0, 0xd2, 0xe7, 0x81, 0x72, 0x67, 0x8f, 0x37, 0xb2, 0xe5, 0x48, 0x4b, 0x39, 0x8f, 0x73, 0xaf,
	0xc3, 0x08, 0x0d, 0x7d, 0x42, 0x83, 0x80, 0xcb, 0x85, 0x4f, 0x28, 0xd5, 0x1a, 0xc2, 0x83, 0x7a,
	0x14, 0x5d, 0x65, 0xcc, 0xad, 0x50, 0x49, 0x1b, 0xac, 0x37, 0x60, 0x42, 0xa2, 0x23, 0x98, 0x6a,
	0x31, 0xe6, 0xd6, 0xdc, 0x0c, 0x30, 0x81, 0xfd, 0xbf, 0xa1, 0xbf, 0x50, 0x15, 0xc2, 0x55, 0x79,
	0x26, 0x69, 0x02, 0x3b, 0x5d, 0xca, 0x63, 0x45, 0x8a, 0x23, 0x52, 0xac, 0x0e, 0xa5, 0x49, 0xf1,
	0x2d, 0xf5, 0x98, 0xce, 0x6c, 0xc4, 0x9c, 0xd6, 0x1b, 0x80, 0x87, 0x6b, 0xc5, 0x22, 0xe4, 0x81,
	0x60, 0xe8, 0x12, 0xfe, 0x6b, 0xe9, 0x7f, 0x19, 0x60, 0xfe, 0xb1, 0xd3, 0xa5, 0x13, 0xbc, 0xbe,
	0x1b, 0x7c, 0x23, 0xbc, 0xa5, 0x71, 0x39, 0x8e, 0xae, 0xb7, 0xc0, 0x15, 0x76, 0xc2, 0xa9, 0xde,
	0x38, 0x5d, 0x69, 0x02, 0xe0, 0xdf, 0x05, 0x1d, 0x7a, 0x01, 0x70, 0xef, 0xb7, 0xa9, 0x3c, 0xae,
	0x55, 0x50, 0x7e, 0x13, 0x66, 0xdb, 0x02, 0xb3, 0x85, 0x9d, 0x73, 0xaa, 0xd7, 0xb2, 0x9f, 0x3f,
	0xbe, 0x27, 0x49, 0x0b, 0x99, 0x24, 0x7e, 0x87, 0x24, 0x3a, 0x14, 0x71, 0xa9, 0xa4, 0xe4, 0x51,
	0xad, 0xfe, 0xa9, 0x5c, 0x7f, 0x9f, 0x19, 0x60, 0x3a, 0x33, 0xc0, 0xd7, 0xcc, 0x00, 0xaf, 0x73,
	0x23, 0x31, 0x9d, 0x1b, 0x89, 0xcf, 0xb9, 0x91, 0xb8, 0xbf, 0xf0, 0x7c, 0xd9, 0x1e, 0x38, 0xb8,
	0xc9, 0xbb, 0xe4, 0x2a, 0x4a, 0xb9, 0xa3, 0x2d, 0xb6, 0xca, 0x3b, 0xd3, 0x2f, 0x69, 0x14, 0xab,
	0x90, 0xe3, 0x90, 0x09, 0x27, 0xb5, 0x78, 0x05, 0xe7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9e,
	0x25, 0x51, 0x76, 0x9c, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	FeedDataByID(ctx context.Context, in *QueryFeedDataRequest, opts ...grpc.CallOption) (*QueryFeedDataResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) FeedDataByID(ctx context.Context, in *QueryFeedDataRequest, opts ...grpc.CallOption) (*QueryFeedDataResponse, error) {
	out := new(QueryFeedDataResponse)
	err := c.cc.Invoke(ctx, "/chainlink.v1beta.Query/FeedDataByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	FeedDataByID(context.Context, *QueryFeedDataRequest) (*QueryFeedDataResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) FeedDataByID(ctx context.Context, req *QueryFeedDataRequest) (*QueryFeedDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FeedDataByID not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_FeedDataByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFeedDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).FeedDataByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chainlink.v1beta.Query/FeedDataByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).FeedDataByID(ctx, req.(*QueryFeedDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chainlink.v1beta.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FeedDataByID",
			Handler:    _Query_FeedDataByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chainlink/v1beta/query.proto",
}

func (m *QueryFeedDataRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFeedDataRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFeedDataRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.FeedId) > 0 {
		i -= len(m.FeedId)
		copy(dAtA[i:], m.FeedId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.FeedId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryFeedDataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFeedDataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFeedDataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.FeedData) > 0 {
		for iNdEx := len(m.FeedData) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FeedData[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryFeedDataRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FeedId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryFeedDataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.FeedData) > 0 {
		for _, e := range m.FeedData {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryFeedDataRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFeedDataRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFeedDataRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeedId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeedId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFeedDataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFeedDataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFeedDataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeedData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeedData = append(m.FeedData, &MsgFeedData{})
			if err := m.FeedData[len(m.FeedData)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
