# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

name: Build

on:
  pull_request:
    branches:
      - "*" 

  jobs:
    lint:
      name: Lint
      runs-on: ubuntu-latest
      timeout-minutes: 5
      steps:
        - uses: actions/checkout@v2
        - name: golangci-lint
          uses: golangci/golangci-lint-action@v2
          with:
            version: v1.36
            args: --timeout=5m
