# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

name: Lint

on:
  pull_request:
    branches:
      - "*" 

jobs:
  lint:
    name: Lint and License Headers
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: v1.36
          args: --timeout=5m
      - name: License Check
        run: make license-check
